#pragma once

enum OBJECT_STATE { PLAY, WAIT, DESTROY };

enum OBJECT_ID {OBJ_PLAYER, OBJ_EFFECT, OBJ_MONSTER, OBJ_GROUND, OBJ_UI, OBJ_END};

enum WEAPON_TYPE {LIGHTNING_WEB, RISING_FIRE};

enum ARMOR_TYPE {FORTH, ULTIMATE};